### PR TITLE
Get the tests running on Travis

### PR DESCRIPTION
**Pull request by edmorley**
@maurodoglio, could you take a quick glance? :-)

* Set execute bit on setup.py and run-tests.py.
* Make run-tests.py exit(1) if tests failed, since it doesn't currently.
* Add a .travis.yml and make a few teaks to get the tests running.

(See individual commit messages for more detail)

At some point later I think it will make sense to use py.test, so run-tests.py can be gotten rid of - and so it's easier to import datasource into the treeherder repo and run with the rest of the py.test tests. But for now this seems like the quickest route to getting something running on Travis.

### CODE REVIEW

**Comment by edmorley** [comment]
Example Travis run (on my repo, since I don't have permissions to enable the Travis hook on this one):
https://travis-ci.org/edmorley/datasource/builds/64745598

**Comment by edmorley** [comment]
Example run before run-tests.py was made to exit(1) if tests failed:
https://travis-ci.org/edmorley/datasource/builds/64742455

And with the fix to make the run turn red:
https://travis-ci.org/edmorley/datasource/builds/64743978

**Comment by maurodoglio** [comment]
It looks very good! Since this library will be integrated in the treeherder repo one day, feel free to drop the comment above.

**Comment by edmorley** [comment]
> Since you now have a requirements file, you could read it from setup.py to build the requirements list.

I was about to do this, but then saw:
http://stackoverflow.com/questions/14399534/how-can-i-reference-requirements-txt-for-the-install-requires-kwarg-in-setuptool
and:
https://caremad.io/2013/07/setup-vs-requirement/
...which is leaving me undecided.

The latter link doesn't really convince me, but the former does mention that reading in the requirements file will break if the requirements file contains comments - and will also potentially confuse PyCharm.

**Comment by edmorley** [comment]
@jeads, I don't suppose you could enable Travis for this repo - I think only the owner has permissions.
To do so, visit https://travis-ci.org/profile and move the slider for this repo to on.
Thanks :-)

**Pull request merged**
